# Логика

In [2]:
import numpy as np
import torch

In [3]:
import sys
sys.path.insert(0, './python')

In [4]:
from fuzzy_torch import logic

## Градиенты

In [5]:
a = torch.tensor(np.array([0.5, 0.9]), requires_grad=True)
b = torch.tensor(np.array([0.7, 0.8]), requires_grad=True)

In [6]:
d = torch.sum(logic.Product.fuzzy_or(a, b))

In [7]:
d.backward()

In [8]:
b.grad

tensor([0.5000, 0.1000], dtype=torch.float64)

## Индикаторные функции

In [10]:
from fuzzy_torch.modules.indicators import Sigmoid, Gaussian

In [11]:
params = Sigmoid((2))

In [12]:
params.linear.weight = torch.nn.Parameter(torch.tensor([[0.5, 0.5]]))
params.linear.bias = torch.nn.Parameter(torch.tensor([-0.5]))

In [13]:
print(params.linear.weight)
print(params.linear.bias)

Parameter containing:
tensor([[0.5000, 0.5000]], requires_grad=True)
Parameter containing:
tensor([-0.5000], requires_grad=True)


In [14]:
params(torch.log(torch.tensor([[0.0000001, 1.0], [200.0, 0.1]])))

tensor([[1.3534e-15],
        [9.8186e-01]], grad_fn=<SigmoidBackward0>)

In [15]:
(torch.zeros(2) + 0.0001) / (torch.zeros(2) + 0.0001)

tensor([1., 1.])

### Простейшие логические выражения

In [ ]:
"""
N_temp = 101
N_wind = 101

temperature_np = np.linspace(-40.0, 60.0, N_temp)
wind_speed_np = np.linspace(0.0, 10, N_wind)

# Сетка значений.
temperature_np_grid, wind_speed_np_grid = np.meshgrid(temperature_np, wind_speed_np)
temperature_np_grid = temperature_np_grid.flatten()[:,None].astype(np.float32)
wind_speed_np_grid = wind_speed_np_grid.flatten()[:,None].astype(np.float32)
"""

In [ ]:
"""
temperature = torch.tensor(temperature_np_grid, requires_grad=True)
wind_speed = torch.tensor(wind_speed_np_grid, requires_grad=True)
"""

In [23]:
# Логические переменные.
I = torch.tensor(np.random.choice([1,0],size=1).astype(np.float32))[:,None]
O = torch.tensor(np.random.choice([1,0],size=1).astype(np.float32))[:,None]
N = torch.tensor(np.random.choice([1,0],size=1).astype(np.float32))[:,None]
T = torch.tensor(np.random.choice([1,0],size=1).astype(np.float32))[:,None]
C = torch.tensor(np.random.choice([1,0],size=1).astype(np.float32))[:,None]
"""
wind_speed_is_high  = Gaussian(1, weight=8.0, offset=1.0)
temperature_is_low  = Sigmoid(1, weight=-0.1, offset=5.0)
temperature_is_high = Sigmoid(1, weight=0.1, offset=35.0)
"""
print(I,O,N,T,C)

tensor([[0.]]) tensor([[0.]]) tensor([[1.]]) tensor([[0.]]) tensor([[1.]])


In [25]:
# Логика.
Logic = logic.Godel

I=torch.tensor(np.array([[0]]).astype(np.float32))
O=torch.tensor(np.array([[1]]).astype(np.float32))
N=torch.tensor(np.array([[1]]).astype(np.float32))
T=torch.tensor(np.array([[1]]).astype(np.float32))
C=torch.tensor(np.array([[1]]).astype(np.float32))
# Алиасы для оераций.
#fz2and  = Logic.fuzzy_2_and
#fz2or   = Logic.fuzzy_2_or
fzand  = Logic.fuzzy_many_and
fzor   = Logic.fuzzy_many_or
fzn = Logic.fuzzy_not
fzimpl = Logic.fuzzy_impl

# Логическое выражение.
v1  = fzand(fzn(I),O,     N,     T,     C)
v2  = fzand(fzn(I),O,     fzn(N),T,     C)
v3  = fzand(I,     O,     fzn(N),T,     C)
v4  = fzand(I,     fzn(O),N,     T,     C)
v5  = fzand(I,     O,     N,     T,     C)
v6  = fzand(I,     O,     N,     T,     fzn(C))
v7  = fzand(fzn(I),O,     fzn(N),fzn(T),fzn(C))
v8  = fzand(fzn(I),O,     fzn(N),T,     fzn(C))
v9  = fzand(fzn(I),O,     fzn(N),fzn(T),C)
v10 = fzand(I,     O,     fzn(N),T,     fzn(C))
v11 = fzand(I,     fzn(O),fzn(N),T,     C)
v12 = fzand(fzn(I),fzn(O),fzn(N),T,     fzn(C))
v13 = fzand(I,     O,     N,     fzn(T),C)
v14 = fzand(I,     O,     N,     fzn(T),fzn(C))
v15 = fzand(I,     O,     fzn(N),fzn(T),C)
v16 = fzand(I,     O,     fzn(N),fzn(T),fzn(C))
v17 = fzand(I,     fzn(O),N,     T,     fzn(C))
v18 = fzand(I,     fzn(O),N,     fzn(T),C)
v19 = fzand(I,     fzn(O),fzn(N),T,     fzn(C))
v20 = fzand(I,     fzn(O),fzn(N),fzn(T),C)
v21 = fzand(fzn(I),O,     N,     T,     fzn(C))
v22 = fzand(fzn(I),O,     N,     fzn(T),C)
v23 = fzand(fzn(I),fzn(O),N,     T,     fzn(C))
v24 = fzand(fzn(I),fzn(O),fzn(N),T,     C)
v25 = fzand(fzn(I),fzn(O),fzn(N),fzn(T),fzn(C))
v28 = fzand(I,     fzn(O),N,     T)
v29 = fzand(I,     fzn(O),N,     T)
v30 = fzand(fzn(I),O,     N,     T)

ANN1  = fzor(v30,v22,v21,v1)
ANN2  = v2
ANN3  = fzor(v3,v15)
ANN4  = fzor(v4,v17,v18,v28)
ANN5  = fzor(v5,v13)
ANN6  = fzor(v6,v14)
ANN7  = v7
ANN8  = v8
ANN9  = v9
ANN10 = fzor(v10,v16)
ANN11 = fzor(v11,v19,v20,v29)
ANN12 = fzor(v12,v23,v24,v25)

print("ANN1: ", ANN1)
print("ANN2: ", ANN2)
print("ANN3: ", ANN3)
print("ANN4: ", ANN4)
print("ANN5: ", ANN5)
print("ANN6: ", ANN6)
print("ANN7: ", ANN7)
print("ANN8: ", ANN8)
print("ANN9: ", ANN9)
print("ANN10: ", ANN10)
print("ANN11: ", ANN11)
print("ANN12: ", ANN12)

ANN1:  tensor([[1.]])
ANN2:  tensor([[0.]])
ANN3:  tensor([[0.]])
ANN4:  tensor([[0.]])
ANN5:  tensor([[0.]])
ANN6:  tensor([[0.]])
ANN7:  tensor([[0.]])
ANN8:  tensor([[0.]])
ANN9:  tensor([[0.]])
ANN10:  tensor([[0.]])
ANN11:  tensor([[0.]])
ANN12:  tensor([[0.]])


In [19]:
close_window_np = close_window.detach().numpy()[:,0].reshape((N_temp, N_wind))

In [20]:
import matplotlib.pyplot as pl

fig = pl.figure()
ax = fig.gca()
cfset = ax.contourf(temperature_np, wind_speed_np, close_window_np, cmap='Blues', levels=100)
ax.set_xlabel('temp')
ax.set_ylabel('wind')

Text(0, 0.5, 'wind')

In [ ]:
x_y = torch.tensor(np.array[[[0.9,0.9,0.8,0.4,0.5],
                             [0.8,0.5,0.9,0.3,0.1],
                             [0.3,0.9,0.6,0.5,0.9],
                             [0.5,0.4,0.5,0.5,0.2],
                             [0.7,0.8,0.8,0.2,0.6]]])
y_z = torch.tensor(np.array[[[0.9,0.8,0.7,0.9,1.0],
                             [0.6,0.4,0.8,0.5,0.6],
                             [0.5,0.2,0.3,0.8,0.7],
                             [0.5,0.9,0.5,0.8,0.4],
                             [1.0,0.6,0.5,0.7,0.4],
                             [0.4,0.5,1.0,0.7,0.8],
                             [0.5,0.8,0.9,0.5,0.4],
                             [0.5,0.6,0.7,0.6,0.5],
                             [0.8,1.0,0.2,0.5,0.6],
                             [0.3,0.5,0.9,0.6,0.8]]])
x_z = compose(x_y,y_z)
print(x_z)